#parser:
#  build: .
#  dockerfile: Dockerfile
#  ports:
#    - "8080:80"

parser:
  image: devastator68/docker_parser
  ports:
    - "8080:80"

hub:
  image: selenium/hub
  restart: always
  links:
    - parser
  ports:
    - "4444:4444"
  expose:
    - "4444"


chrome1:
  image: selenium/node-chrome
  restart: always
  links:
    - hub

chrome2:
  image: selenium/node-chrome
  restart: always
  links:
    - hub