parser:
  build: .
  dockerfile: Dockerfile
  ports:
    - "8080:80"

hub:
  image: selenium/hub
  restart: always
  ports:
    - "4444:4444"
  expose:
    - "4444"
  links:
    - parser

chrome:
  image: selenium/node-chrome
  restart: always
  links:
    - hub