parser:
  build: .
  dockerfile: Dockerfile
  ports:
    - "8080:80"

hub:
  image: selenium/hub
  ports:
    - "4444:4444"
  links:
    - parser

chrome:
  image: selenium/node-chrome
  ports:
    - "5555:5555"
  links:
    - hub